[package]
name = "egpu-init"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = { version = "0.36", features = ["panic_handler", "alloc", "global_allocator"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true