[package]
name = "egpu-init"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = { version = "0.36", features = ["alloc", "global_allocator", "panic_handler", "logger"] }
uefi-raw = "0.13"
log = "0.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true